### PR TITLE
Return an empty file range for SHT_NOBITS sections

### LINKED ISSUE #252: Incorrect file_range for ELF sections with type SHT_NOBITS
I've noticed that goblin returns a non-empty range when `file_range()` is called on a section header with type `SHT_NOBITS`.

From what I understand, these sections don't have any data in the file itself, and only exist in memory. I would expect that the returned range is empty in that case. The returned file range also overlaps with the file range of the next section.

I would suggest that the `file_range` function should check the type, and return an empty range in case its NOBITS. If that's ok I can do a PR.

### PR DESCRIPTION
**Pull request by Tiwalun**
ELF sections with type SHT_NOBITS only exist in memory, and
don't contain any data in the ELF file itself. The range
returned by `file_range()` should be empty for such sections.

The previously returned range was wrong, and overlapped
the file range of the next section.

Fixes #252.

### CODE REVIEW

File: src/elf/section_header.rs [hunk 1]
```diff
@@ -428,7 +428,13 @@ if_alloc! {
         }
         /// Returns this section header's file offset range
         pub fn file_range(&self) -> Range<usize> {
-            self.sh_offset as usize..(self.sh_offset as usize).saturating_add(self.sh_size as usize)
+            // Sections with type SHT_NOBITS have no data in the file itself,
+            // they only exist in memory.
+            if self.sh_type == SHT_NOBITS {
+                self.sh_offset as usize..self.sh_offset as usize
```
Comment (m4b) [inline src/elf/section_header.rs:434]: is returning a 0 range going to cause issues? ideally we'd return an `Option<Range<usize>>` i think, but that would be breaking change. Might be worth it though?

Comment (m4b) [reply src/elf/section_header.rs:434]: ok i don't think this should be `self.sh_offset..self.sh_offset`; if sh_offset is non-zero you can get e.g., `10..10` or whatever, that is an empty range but will cause a panic if it's larger than buffer, i.e., this panics:
```rust
    let foo = [1, 2, 3];
    let x = &foo[10..10];
```

So i think it's better to return `0..0` ? or Option.

Comment (Tiwalun) [reply src/elf/section_header.rs:434]: Oh, I didn't expect the empty range to panic when it's out of bounds.

I think `0..0`would be confusing as well, if someone looks at the start field of the range to decide where the data in the file starts.

An Option would be the solution, in my opinion.

Comment (m4b) [reply src/elf/section_header.rs:434]: Ok let's make it option, it's the right thing to do :) this will be a breaking change so unless you are in urgent need of a release, i may wait a bit to roll up other potential changes, or make other breaking changes

Comment (Tiwalun) [reply src/elf/section_header.rs]: I don't need it urgently, manually checking the section type is an easy workaround.

File: src/elf/section_header.rs [hunk 2]
```diff
@@ -426,9 +426,16 @@ if_alloc! {
                 sh_entsize: 0,
             }
         }
-        /// Returns this section header's file offset range
-        pub fn file_range(&self) -> Range<usize> {
-            self.sh_offset as usize..(self.sh_offset as usize).saturating_add(self.sh_size as usize)
+        /// Returns this section header's file offset range,
+        /// if the section occupies space in fhe file.
```
Comment (m4b) [inline src/elf/section_header.rs:430]: typo: `fhe` -> `the`

**Review by m4b — APPROVED** [review]
if you want to fix the typo that would be great, otherwise LGTM

**Comment by m4b** [comment]
thanks for this PR ! :)
