### PR TITLE
Fixed #267

### LINKED ISSUE #267: Failed to parse PE of loaded module
I thought goblin was the only library that could parse PE correctly, but unfortunately after getting the list of modules loaded from PEB, trying to parse from the DllBase address seems to fail halfway.
(fyi, pelite succeeded in parsing this, but failed to parse the system DLL. Goblin is perfect for parsing from disc dll.)
Here is the procedure for reproducing the error.

put this in `Cargo.toml`
```
[dependencies]
anyhow = "1.0.40"
goblin = "0.3.4"
ntapi = { version = "0.3.6", features = ["nightly"] }
winapi = "0.3.9"
```
then, code like a this:
```rust
use std::fs::File;
use std::io::prelude::*;

use anyhow::*;
use ntapi::{
    ntldr::LDR_DATA_TABLE_ENTRY,
    ntpebteb::PEB,
    winapi_local::um::winnt::__readgsqword
};
use winapi::ctypes::c_void;

pub fn get_binary_from_file(file_name: impl Into<String>) -> Result<Vec<u8>> {
    let file_name = file_name.into();
    let mut f = File::open(&file_name)
        .with_context(|| format!("could not opening the file: {}", &file_name))?;
    let mut buffer = Vec::new();
    f.read_to_end(&mut buffer)
        .with_context(|| format!("could not reading from the file: {}", &file_name))?;
    Ok(buffer)
}

pub fn ptr_to_u8slice(p: *mut c_void) -> &'static [u8] {
    unsafe { std::mem::transmute_copy::<*mut c_void, &[u8]>(&p) }
}

fn main() -> Result<()>{
    unsafe {
        let ntdll_buffer = get_binary_from_file("c:\\windows\\system32\\ntdll.dll")?;
        // this works :3
        let _ = goblin::pe::PE::parse(ptr_to_u8slice(&ntdll_buffer[0] as *const _ as _))?;
        println!("parsed!");

        let ppeb = __readgsqword(0x60) as *mut PEB;

        let p_peb_ldr_data = (*ppeb).Ldr;
        let mut module_list = (*p_peb_ldr_data).InLoadOrderModuleList.Flink as *mut LDR_DATA_TABLE_ENTRY;

        while !(*module_list).DllBase.is_null() {
            let dll_base = (*module_list).DllBase;

            module_list = (*module_list).InLoadOrderLinks.Flink as *mut LDR_DATA_TABLE_ENTRY;

            // this not works :<
            let _ = goblin::pe::PE::parse(ptr_to_u8slice(dll_base))?;
            println!("parsed!");
        }

        Ok(())
    }
}
```

example output (got this error on my env):
```
parsed!
Error: Malformed entity: Cannot find name from rva 0x40 in sections: [SectionTable { name: [46, 116, 101, 120, 116, 0, 0, 0], real_name: None, virtual_size: 485194, virtual_address: 4096, size_of_raw_data: 485376, pointer_to_raw_data: 1024, pointer_to_relocations: 0, pointer_to_linenumbers: 0, number_of_relocations: 0, number_of_linenumbers: 0, characteristics: 1610612768 }, SectionTable { name: [46, 114, 100, 97, 116, 97, 0, 0], real_name: None, virtual_size: 100872, virtual_address: 491520, size_of_raw_data: 101376, pointer_to_raw_data: 486400, pointer_to_relocations: 0, pointer_to_linenumbers: 0, number_of_relocations: 0, number_of_linenumbers: 0, characteristics: 1073741888 }, SectionTable { name: [46, 100, 97, 116, 97, 0, 0, 0], real_name: None, virtual_size: 904, virtual_address: 593920, size_of_raw_data: 512, pointer_to_raw_data: 587776, pointer_to_relocations: 0, pointer_to_linenumbers: 0, number_of_relocations: 0, number_of_linenumbers: 0, characteristics: 3221225536 }, SectionTable { name: 
[46, 112, 100, 97, 116, 97, 0, 0], real_name: None, virtual_size: 37020, virtual_address: 598016, size_of_raw_data: 37376, pointer_to_raw_data: 588288, pointer_to_relocations: 0, pointer_to_linenumbers: 
0, number_of_relocations: 0, number_of_linenumbers: 0, characteristics: 1073741888 }, SectionTable { name: [46, 114, 101, 108, 111, 99, 0, 0], real_name: None, virtual_size: 2076, virtual_address: 638976, size_of_raw_data: 2560, pointer_to_raw_data: 625664, pointer_to_relocations: 0, pointer_to_linenumbers: 0, number_of_relocations: 0, number_of_linenumbers: 0, characteristics: 1107296320 }]
```

I don't know if this only happens in my environment.
Or is this not a problem and my code is wrong?

thanks in advance!

### PR DESCRIPTION
**Pull request by 2vg**
related: https://github.com/m4b/goblin/issues/267

The problem here was solved by using parse_with_otps.
I had some time, so I debugged and confirmed that the problematic code I presented didn't cause any problems.
No tests were added because I didn't have time to write the tests.
If you have time, please help me :<

### CODE REVIEW

**Comment by m4b** [comment]
@2vg thank you for the patch! LGTM, looks like rustfmt failed, can you run it on that file? thanks, once CI passes can merge

**Review by m4b — APPROVED** [review]
just needs rustfmt; if you don't want me to squash, you can just ammend and force push the rustfmt change if you prefer

File: src/pe/import.rs [hunk 1]
```diff
@@ -227,11 +227,12 @@ impl<'a> SyntheticImportDirectoryEntry<'a> {
                 opts,
             ) {
                 debug!("Synthesizing lookup table imports for {} lib, with import lookup table rva: {:#x}", name, import_lookup_table_rva);
-                let import_lookup_table = SyntheticImportLookupTableEntry::parse::<T>(
+                let import_lookup_table = SyntheticImportLookupTableEntry::parse_with_opts::<T>(
```
Comment (m4b) [inline src/pe/import.rs:230]: @ko1N since you implemented this feature, does this look correct to you?

Comment (m4b) [reply src/pe/import.rs:230]: I don't know why not passing the opts along would hurt, and seems to resolve @2vg 's issue (though I confess I'm not sure what was the exact problem), so I assume this is ok :)

Comment (ko1N) [reply src/pe/import.rs:230]: Yes, the table entry will not be resolved properly when not passing the opts in case rva_resolve is disabled.

Since we left all regular `parse` functions untouched (as in the regular/"old" behavior) this was an oversight on my part. Luckily those changes could've only caused trouble when using mapped binary dumps. Either way, the change look totally fine to me.

**Comment by m4b** [comment]
@2vg thank you for your patience, merged; would you like a new release? I will likely add this to the 0.4 release, which has one (minor) breaking change, but which should not affect your usecase at all (PE, iiuc)

**Comment by m4b** [comment]
Ok 0.4.0 is out :)
