### PR TITLE
pe.export: fix reexport dll and ordinal

### LINKED ISSUE #160: reexport lib name may be truncated
Reviewing the exports of `kernel32.dll`, it looks like the `lib` field of reexports may be truncated by one character:

image

I believe the expected value should be `NTDLL`:

image

### PR DESCRIPTION
**Pull request by lzybkr**
Fix #160

### CODE REVIEW

File: src/pe/export.rs [hunk 1]
```diff
@@ -157,23 +157,21 @@ impl<'a> scroll::ctx::TryFromCtx<'a, scroll::Endian> for Reexport<'a> {
...
+                    break;
+                }
+                let len = reexport_len - o - 1;
+                let rest: &'a [u8] = bytes.pread_with(o + 1, len)?;
                 debug!("rest: {:?}", &rest);
-                let len = rest.len() - 1;
                 if rest[0] == b'#' {
-                    // UNTESTED
-                    let ordinal = rest.pread_with::<&str>(1, scroll::ctx::StrCtx::Length(len))?;
+                    let ordinal = rest.pread_with::<&str>(1, scroll::ctx::StrCtx::Length(len - 1))?;
```
Comment (philipc) [inline src/pe/export.rs]: Have you tested this? It doesn't seem correct to me. `rest` is already starting at `o + 1`, so I don't think we need the additional `1` offset here.

File: src/pe/export.rs [hunk 2]
```diff
@@ -157,23 +157,21 @@ impl<'a> scroll::ctx::TryFromCtx<'a, scroll::Endian> for Reexport<'a> {
...
                     let ordinal = ordinal.parse::<u32>().map_err(|_e| error::Error::Malformed(format!("Cannot parse reexport ordinal from {} bytes", bytes.len())))?;
-                    // FIXME: return size
-                    return Ok((Reexport::DLLOrdinal { export: dll, ordinal: ordinal as usize }, 0))
+                    return Ok((Reexport::DLLOrdinal { export: dll, ordinal: ordinal as usize }, reexport_len + 1))
```
Comment (philipc) [inline src/pe/export.rs]: This is an existing problem, but this enum variant makes no sense to me. I think it would be better as:
```
Reexport::DLLOrdinal { ordinal: ordinal as usize, lib: dll }
```

File: src/pe/export.rs (hunk 1 above)
Comment (lzybkr) [reply src/pe/export.rs]: I did test. I changed `rest` to start after the `.` - so that's `o + 1`.

In the ordinal case, we also need to skip the `#` (start at offset 1), and the len includes the `#`, so subtract 1.

```
#175 PS> .\target\debug\pedump.exe C:\windows\System32\certcli.dll | sls mySan

Export { name: Some("mySanitizeName"), offset: 420153, rva: 423225, size: 0, reexport: Some(DLLOrdinal { export: "CERTCA", ordinal: 831 }) }
Export { name: Some("mySanitizedNameToDSName"), offset: 420189, rva: 423261, size: 0, reexport: Some(DLLOrdinal { export: "CERTCA", ordinal: 832 }) }
Export { name: Some("mySanitizedNameToShortName"), offset: 420228, rva: 423300, size: 0, reexport: Some(DLLOrdinal { export: "CERTCA", ordinal: 833 }) }

#176 PS> link /dump /exports C:\windows\System32\certcli.dll | sls mySan

    349   A0          mySanitizeName (forwarded to CERTCA.#831)
    350   A1          mySanitizedNameToDSName (forwarded to CERTCA.#832)
    351   A2          mySanitizedNameToShortName (forwarded to CERTCA.#833)
```

Comment (philipc) [reply src/pe/export.rs]: Ah great, my mistake.

File: src/pe/export.rs (hunk 2 above)
Comment (lzybkr) [reply src/pe/export.rs]: That seems like a reasonable change, but it would be an api breaking change. Is that OK for this PR?

Comment (philipc) [reply src/pe/export.rs]: The off-by-one bug and this enum variant were both added in fe11bb05. Since this code doesn't work and hasn't ever worked since this enum variant was added, I think it is fine.

Comment (m4b) [reply src/pe/export.rs]: Yes ok with break and fix, thanks for this PR and fixing this very long-standing bug I added :D

Comment (lzybkr) [reply src/pe/export.rs]: Great, I made the change. And thanks for this very useful crate.
